version: '3'
services:
  postgresql:
    image: postgres
    restart: always 
    env_file:
      - .db.env
    ports: 
      - "5432:5432"
  redis:
    image: redis:3.2-alpine
    command: redis-server --port 7479
    ports:
      - "7479:7479"
    restart: always
  web:
    build: .
    restart: always
    command: puma -C config/puma.rb
    volumes:
      - ./api:/api
    ports:
      - "4567:4567"
    env_file:
      - .env
    depends_on:
      - redis
      - postgresql
    tty: true
    stdin_open: true
  runner:
    build: .
    restart: always
    command: rake db:schedule
    volumes:
      - ./api:/api
    env_file:
      - .env
    depends_on:
      - redis
      - postgresql
    tty: true
    stdin_open: true
