require 'rspec/core/rake_task'
require File.expand_path(File.join(__dir__, 'db', 'seed.rb'))

namespace :db do
  desc 'Seed database'
  task :seed do
    Seed::populateSQL
    Seed::populateCache
  end

  desc 'Schedule seed'
  task :schedule do
    Rake::Task["db:seed"].invoke
    loop do
      Seed::populateSQL
      puts "Waiting"
      sleep(ENV['DB_SEED'].to_i)
    end
  end
end

namespace :test do
  desc "All tests"
  task :all do
    RSpec::Core::RakeTask.new(:spec) do |t|
      t.pattern = 'spec/**/*_spec.rb'
    end
    Rake::Task["spec"].execute
  end

  task :controllers do
    RSpec::Core::RakeTask.new(:spec) do |t|
      t.pattern = 'spec/controller/*_spec.rb'
    end
    Rake::Task["spec"].execute
  end

  task :models do
    RSpec::Core::RakeTask.new(:spec) do |t|
      t.pattern = 'spec/model/*_spec.rb'
    end
    Rake::Task["spec"].execute
  end
end